version: "3"

services:
  postgres:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gili
      POSTGRES_PASSWORD: my-pass
      POSTGRES_DB: djangodb
    networks:
      - django
  web:
    image: gilibe/django-project:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - django

networks:
  django: